[package]
name = "zapdrop"
version = "0.1.0"
description = "Offline local-network file sharing for nearby PCs"
authors = ["Nexuss"]
edition = "2021"
rust-version = "1.77.2"
license = "MIT"

[lib]
name = "zapdrop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
base64 = "0.22"
chacha20poly1305 = "0.10"
directories = "6"
fs2 = "0.4"
hkdf = "0.12"
ed25519-dalek = "2"
keyring = "3"
local-ip-address = "0.6"
mdns-sd = "0.21"
rand_core = { version = "0.6", features = ["getrandom"] }
thiserror = "2"
tokio = { version = "1", features = ["net", "time", "sync", "rt-multi-thread"] }
unicode-normalization = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
x25519-dalek = { version = "2", features = ["static_secrets"] }
zeroize = "1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
swarm-v2 = []
swarm-tree-mesh = ["swarm-v2"]
